@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/history HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"subject":"sint",
"comments":"Incididunt est commodo magna aliquip labore id.",
"status":"inclf"
}

###

GET {{HOST}}/history? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/history?subject=sint&comments=Incididunt&status=inclf HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/history/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/history/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"subject":"sint",
"comments":"Incididunt est commodo magna aliquip labore id.",
"status":"inclf"
}
###
PATCH {{HOST}}/history/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"subject":"sint",
"comments":"Incididunt est commodo magna aliquip labore id.",
"status":"inclf"
}
###
DELETE {{HOST}}/history/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
