@HOST1 = https://goldfish-app-l4bmd.ondigitalocean.app
@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST1}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/users HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"inclf",
"firstname":"laboris",
"password":"ucode1234",
"email":"eu@ucode.ai1",
"mobile":"duis6",
"referral":"reprehenderit@ucode.ai"
}

###

#MAIN REGISTRATION for NODEJS VERSION
POST {{HOST}}/users/reg HTTP/1.1
content-type: application/json
    
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408252",
"referral":"a@aaa.com"
}
###
#MAIN REGISTRATION for Java Spring boot
POST {{HOST}}/users/reg HTTP/1.1
content-type: application/json
 
{
"email":"boss11@harimaumint.com",
"password":"123456",
"firstname":"Harimau",
"lastname":"Mint",
"usertype":"0",
"mobile":"601764018250",
"referral":"1@harimaumint.com"
}
###

GET {{HOST}}/users? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users?usertype=1&lastname=inclf&firstname=laboris&email=eu@ucode.a&mobile=duis6&referral=reprehende HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"inclf",
"firstname":"laboris",
"password":"ucode1234",
"email":"eu@ucode.ai1",
"mobile":"duis6",
"referral":"reprehenderit@ucode.ai"
}
###
PATCH {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"inclf",
"firstname":"laboris",
"password":"ucode1234",
"email":"eu@ucode.ai1",
"mobile":"duis6",
"referral":"reprehenderit@ucode.ai"
}
###
DELETE {{HOST}}/users/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
